# Generated by Django 3.1.4 on 2021-11-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('text_state', models.TextField(verbose_name='Текст статьи')),
                ('text_state_ru', models.TextField(null=True, verbose_name='Текст статьи')),
                ('text_state_en', models.TextField(null=True, verbose_name='Текст статьи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_ru', models.DateField(null=True, verbose_name='Дата')),
                ('date_en', models.DateField(null=True, verbose_name='Дата')),
                ('author', models.EmailField(max_length=254, verbose_name='email автора')),
                ('image', models.ImageField(upload_to='News_shots/', verbose_name='Фотография')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя сервиса')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Имя сервиса')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Имя сервиса')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('cost', models.IntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Цена')),
                ('size', models.PositiveSmallIntegerField(help_text='указывать размер в футах', verbose_name='Размер номера')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Кол-во персон')),
                ('bed', models.CharField(max_length=150, verbose_name='Краткое описание спального места')),
                ('bed_ru', models.CharField(max_length=150, null=True, verbose_name='Краткое описание спального места')),
                ('bed_en', models.CharField(max_length=150, null=True, verbose_name='Краткое описание спального места')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('img', models.ImageField(upload_to='Rooms_shots/', verbose_name='Фотография комнаты')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('reservaton', models.BooleanField(verbose_name='Резервация')),
                ('services', models.ManyToManyField(to='hotel_list.Services')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('text_ru', models.TextField(max_length=5000, null=True, verbose_name='Сообщение')),
                ('text_en', models.TextField(max_length=5000, null=True, verbose_name='Сообщение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_ru', models.DateField(null=True, verbose_name='Дата')),
                ('date_en', models.DateField(null=True, verbose_name='Дата')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_list.reviews', verbose_name='Родитель')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_list.rooms', verbose_name='комната')),
                ('room_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_list.rooms', verbose_name='комната')),
                ('room_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_list.rooms', verbose_name='комната')),
            ],
            options={
                'verbose_name': 'Отзыв к комнате',
                'verbose_name_plural': 'Отзывы к комнатам',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_list.rooms', verbose_name='комната')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_list.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='NewsShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_list.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фотографии для новости',
                'verbose_name_plural': 'Фотографии для новостей',
            },
        ),
        migrations.CreateModel(
            name='NewsReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('text_ru', models.TextField(max_length=5000, null=True, verbose_name='Сообщение')),
                ('text_en', models.TextField(max_length=5000, null=True, verbose_name='Сообщение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('date_ru', models.DateField(null=True, verbose_name='Дата')),
                ('date_en', models.DateField(null=True, verbose_name='Дата')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_list.news', verbose_name='фильм')),
                ('news_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_list.news', verbose_name='фильм')),
                ('news_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_list.news', verbose_name='фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_list.newsreviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв к новости',
                'verbose_name_plural': 'Отзывы к новостям',
            },
        ),
    ]
